export const BIND_ACCOUNT_REQUEST = 'PRO/BIND_ACCOUNT_REQUEST';
export const BIND_ACCOUNT_SUCCESS = 'PRO/BIND_ACCOUNT_SUCCESS';
export const BIND_ACCOUNT_FAILURE = 'PRO/BIND_ACCOUNT_FAILURE';

export const UPDATE_BOUND_REQUEST = 'PRO/UPDATE_BOUND_REQUEST';
export const UPDATE_BOUND_SUCCESS = 'PRO/UPDATE_BOUND_SUCCESS';
export const UPDATE_BOUND_FAILURE = 'PRO/UPDATE_BOUND_FAILURE';

export const DELETE_BOUND_REQUEST = 'PRO/DELETE_BOUND_REQUEST';
export const DELETE_BOUND_SUCCESS = 'PRO/DELETE_BOUND_SUCCESS';
export const DELETE_BOUND_FAILURE = 'PRO/DELETE_BOUND_FAILURE';

export const GET_BOUND_REQUEST = 'PRO/GET_BOUND_REQUEST';
export const GET_BOUND_SUCCESS = 'PRO/GET_BOUND_SUCCESS';
export const GET_BOUND_FAILURE = 'PRO/GET_BOUND_FAILURE';

export const GET_KEYSTORE_REQUEST = 'PRO/GET_KEYSTORE_REQUEST';
export const GET_KEYSTORE_SUCCESS = 'PRO/GET_KEYSTORE_SUCCESS';
export const GET_KEYSTORE_FAILURE = 'PRO/GET_KEYSTORE_FAILURE';

export const CREATE_ACCOUNT_BY_SYSTEM_REQUEST = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_REQUEST';
export const CREATE_ACCOUNT_BY_SYSTEM_SUCCESS = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_SUCCESS';
export const CREATE_ACCOUNT_BY_SYSTEM_FAILURE = 'PRO/CREATE_ACCOUNT_BY_SYSTEM_FAILURE';

export const GET_ACCOUNT_INFO_REQUEST = 'PRO/GET_ACCOUNT_INFO_REQUEST';
export const GET_ACCOUNT_INFO_SUCCESS = 'PRO/GET_ACCOUNT_INFO_SUCCESS';
export const GET_ACCOUNT_INFO_FAILURE = 'PRO/GET_ACCOUNT_INFO_FAILURE';


export const RPC_REQUEST_FAILURE = 'PRO/RPC_REQUEST_FAILURE';